### ISSUE TITLE
Where do I save the pkgs  downloads ?

### ISSUE THREAD

**Issue by ToniFabri** [victorrjimenezz/PS4-4PT#12]
where do I save the package downloads? I installed RDR2 85gb, when it finished, it gave an error when installing, then it disappeared

**Comment by victorrjimenezz** [comment]
PKG Downloads are stored in /user/app, if the download disappeared and it is also not in that directory, it might be that the app detected the PKG as invalid, either by mistake or rightfully. Could you please attach the logfile?

**Comment by ToniFabri** [comment]
> Os downloads de PKG são armazenados em /user/app, se o download desapareceu e também não estiver nesse diretório, pode ser que o aplicativo tenha detectado o PKG como inválido, seja por engano ou por estar corrompido. Poderia anexar o arquivo de log? Além disso, que erro deu?

[2022-2-5_16.56.47.log](https://github.com/victorrjimenezz/PS4-4PT/files/8008532/2022-2-5_16.56.47.log)

**Comment by victorrjimenezz** [comment]
I see that some pkgs are not being downloaded because of an error, download bytes function interprets 200 status code as invalid, when it is valid. I have fixed this and the fix will be delivered in the next update.

Regarding the RDR2 game. Could you elaborate a little bit on the issue?
To my understanding you downloaded RDR2 using the 4PT app. It threw an error during the installation and then it disappeared from the download view. Is it correct?

Also, has the pkg been deleted from the /user/app folder?

Thank you for your feedback! :)

**Comment by ToniFabri** [comment]
> Vejo que alguns pkgs não estão sendo baixados por causa de um erro, a função download bytes interpreta o código de status 200 como inválido, quando é válido. Eu corrigi isso e a correção será entregue na próxima atualização.
> 
> Em relação ao jogo RDR2. Poderia detalhar um pouco o assunto? Pelo que entendi, você baixou o RDR2 usando o aplicativo 4PT. Ele deu um erro durante a instalação e depois desapareceu da visualização de download. Está correto?
> 
> Além disso, o pacote foi excluído da pasta /user/app?
> 
> Obrigado pelo seu feedback! :)

Yes, message failed install, not pkg in user/app CUSA08519

**Comment by victorrjimenezz** [comment]
> > Vejo que alguns pkgs não estão sendo baixados por causa de um erro, a função download bytes interpreta o código de status 200 como inválido, quando é válido. Eu corrigi isso e a correção será entregue na próxima atualização.
> > Em relação ao jogo RDR2. Poderia detalhar um pouco o assunto? Pelo que entendi, você baixou o RDR2 usando o aplicativo 4PT. Ele deu um erro durante a instalação e depois desapareceu da visualização de download. Está correto?
> > Além disso, o pacote foi excluído da pasta /user/app?
> > Obrigado pelo seu feedback! :)
> 
> Yes, message failed install, not pkg in user/app CUSA08519

most likely the app detected it as corrupted and deleted it, has it happened more than once?
