### ISSUE TITLE
[Feature Request] Custom port support

### ISSUE THREAD

**Issue by method4tax** [victorrjimenezz/PS4-4PT#14]
Hey!

it seems like when you have a colon definition for defining a port in the url, then this colon gets url-encoded instead of staying a literal colon.

e.g.: `http://myserver:8000/` becomes `http://myserver%3A8000/`

cheers!

**Comment by victorrjimenezz** [comment]
Hi!! Connection to servers is only implemented on 80 (http) and 443 (https), custom ports has not been implemented yet. I've changed this issue to feature request and will work on it!

**Comment by victorrjimenezz** [comment]
the issue has been fixed in the last commit. Now repositories can be added on any custom port! thanks for noticing and sharing :)
I will release the fix in the next 2.5 update!

**Comment by method4tax** [comment]
@victorrjimenezz actually this worked before the url-encode. but it is fine for me. i've create a separate hostname in my local network.

**Comment by victorrjimenezz** [comment]
> @victorrjimenezz actually this worked before the url-encode. but it is fine for me. i've create a separate hostname in my local network.

You’re right, had not realised!
anyways the fix will be released with the next update :)
Thank you for sharing

**Comment by victorrjimenezz** [comment]
Marking this as closed since it has been fixed!
