### ISSUE TITLE
v2.00 INVALID URL error with custom repo

### ISSUE THREAD

**Issue by nickyg666** [victorrjimenezz/PS4-4PT#2]
hello again! upon trying to run v2.00 with custom repo.yml, I am greeted with INVALID URL when adding repo.
repo is reachable from other places, as well as in previous version 1.0.2. I have tried editing the YAML down to just the new bare minimum of your YAML config spec, with same result. I have also tried hosting over https with local generated openssl key and openssl server. I have tried specifying just http:// in the add bar. Can't get past this. I haven't tried a dummy index.html or .php yet, could that be the issue? 
to reiterate, 1.0.2 is working just swell for me, with both being installable side by side. I did most v2.00 testing without 1.0.2 installed. I have to be missing something really simple, and I feel dumb for raising this as an issue. I did attempt to get additional testers for v2.00 before raising the issue, to no avail.
also, have to mention: love the improvements, UI is much more finished feeling. You're doing amazing work!
EDIT: it's also very nice that on failed repo add it doesn't crash like it used to!!

**Comment by victorrjimenezz** [comment]
Could you attach the repo.yml file you are using?

**Comment by nickyg666** [comment]
Yes, here are both. .new is the one that I modified for 2.00, but it didn't work so i reverted to the backup of 1.0.2 working yaml
[repos.zip](https://github.com/victorrjimenezz/PS4-4PT/files/7961078/repos.zip)
github wanted a zip so they are in there.

**Comment by victorrjimenezz** [comment]
are you using an ip or a domain?

**Comment by nickyg666** [comment]
ip, plain http server over LAN. was ssl implemented as a replacement to
regular http?

**Comment by victorrjimenezz** [comment]
no it was not, i found the issue and fixed it, will be releasing the fix in a few minutes, the implementation of regex URL verification only returned it as valid if it was a domain, not an ip!

**Comment by nickyg666** [comment]
cool! glad i could help!
