### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by Mad-sl67** [victorrjimenezz/PS4-4PT#28]
2 months is passed and the new update is not release yet
I just want to know are you still working on it ?

**Comment by victorrjimenezz** [comment]
Hi!! Yes, I’m still working on it. The thing is that right now I’m in my college semester and focusing on my assignments and exams, so I do not have that much time to focus on the app. When the the summer vacation comes I’ll focus again and I’ll release a bunch of updates. Sorry for taking so long, hope the wait makes it worth it!

**Comment by Mad-sl67** [comment]
I see brother
And good luck for the exams, i wish you the best
