### ISSUE TITLE
[bug] Issue on the mkdirs function when initializing the app

### ISSUE THREAD

**Issue by victorrjimenezz** [victorrjimenezz/PS4-4PT#4]
it happens only to a fraction of users, it is a known issue pending fix

**Comment by D3ATHLY** [comment]
+1

**Comment by victorrjimenezz** [comment]
> +1

Hi!! Are you experiencing the issue? Could you provide me a little more detail?
When the app is installed, does the directory /user/app/PAPT00230/ exist?
Does it say that there was an error when making the directories?

**Comment by D3ATHLY** [comment]
> > +1
> 
> Hi!! Are you experiencing the issue? Could you provide me a little more detail? When the app is installed, does the directory /user/app/PAPT00230/ exist? Does it say that there was an error when making the directories?

Hello, yes there is no created folder of PAPT00230, aaand yes i am get error when try open 4pt app, its force closing and giving error like u...

**Comment by D3ATHLY** [comment]
![1643573993334942877070076277794](https://user-images.githubusercontent.com/1476660/151716211-e2e239e7-8211-4e4a-aa5b-6a412ada4f0c.jpg)
![16435740138988023936954832187341](https://user-images.githubusercontent.com/1476660/151716223-051ce99a-f5a1-4edb-982c-e9379d583868.jpg)
![Uploading 16435740327398761125891287338338.jpg…]()

**Comment by D3ATHLY** [comment]
#
![16435740958043317968669051586301](https://user-images.githubusercontent.com/1476660/151716264-a0b0f6ed-a4db-4659-9702-436334d92165.jpg)

**Comment by victorrjimenezz** [comment]
Thank you!! This information is very useful for me :)
Could you try to use this version:
https://www.4pt-project.com/4PT-FIXED.pkg ?
